### ISSUE TITLE
KeyError: 'geocode' when running library in mode 1 & 2

### ISSUE THREAD

**Issue by ryanbaumann** [googlemaps/python-high-volume-address-validation-library#6]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Address Validation API
2. Mac OS 
3. High Volume AV version `v0.5`

#### Steps to reproduce

  1. Run CSV with 10 addresses through library `python 3 main.py` with config set to option 1 or 2 
  2. During "getting verdict" stage while running `main.py`, one address returns an error (the third) resulting in a failed job and no output results to csv:
```
Completed: [==========                                        ]  20%Unexpected err=KeyError('geocode'), type(err)=<class 'KeyError'>
No latitude or longitude found
Unexpected err=KeyError('geocode'), type(err)=<class 'KeyError'>
Error happened when calling the main functions
Traceback (most recent call last):
  File "/Users/ryanbaumann/projects/python-high-volume-address-validation-library/src/main.py", line 179, in <module>
    (HighVolumeAVMain.read_and_store_addresses() and HighVolumeAVMain.parse_av_response())
  File "/Users/ryanbaumann/projects/python-high-volume-address-validation-library/src/main.py", line 79, in parse_av_response
    parsed_response=av_result_parser_load.parse_av_response(address_validation_result)
  File "/Users/ryanbaumann/projects/python-high-volume-address-validation-library/src/av_result_parser.py", line 93, in parse_av_response
    parsed_result.update(av_result_parser_class.get_latlong(address_validation_result))
  File "/Users/ryanbaumann/projects/python-high-volume-address-validation-library/src/av_result_parser.py", line 229, in get_latlong
    if LOCATION in address_validation_result[RESULT][GEOCODE]:
KeyError: 'geocode'
```

### Expected behavior
* Library should fail gracefully and continue to an end resut with appropriate error message

### Next Steps
* Investigating specific address failure and result from geocoding API

cc/ @anubis05 @anglarett @henrikvalv3

**Comment by wangela** [comment]
@ryanbaumann Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by anglarett** [comment]
Thanks Ryan for reporting,

Would you be able to share the Address Validation API call details (address + region) or input csv to reproduce the error? 
First guess would be a missing exception on the returned Address Validation payload.

**Comment by henrikvalv3** [comment]
Hi @ryanbaumann, thanks for reporting! 

I've added better handling in commit aedb9f336cc0ee67f3cae601bfe201515023eca8 within av_result_parser.py for scenarios where the API does not respond with a geocode.

Please try again with this update.

Cheers!
